//
//  ListePays.swift
//  LivreRecette
//
//  Created by Dorian George on 9/16/23.
//

import Foundation

class Pays {
    
    public func getPays(codePays:String) -> String
    {
        switch codePays{
            case "AF" : return "Afghanistan"
            case "ZA" : return "Afrique du Sud"
            case "AX" : return "Åland, Îles"
            case "AL" : return "Albanie"
            case "DZ" : return "Algérie"
            case "FR" : return "France"
            case "DE" : return "Allemagne"
            case "DD" : return "Allemagne de l'EST"
            case "AD" : return "Andorre"
            case "AO" : return "Angola"
            case "AI" : return "Anguilla"
            case "AQ" : return "Antarctique"
            case "AG" : return "Antigua et Barbuda"
            case "AN" : return "Antilles néerlandaises"
            case "SA" : return "Arabie Saoudite"
            case "AR" : return "Argentine"
            case "AM" : return "Arménie"
            case "AW" : return "Aruba"
            case "AU" : return "Australie"
            case "AT" : return "Autriche"
            case "AZ" : return "Azerbaïdjan"
            case "BS" : return "Bahamas"
            case "BH" : return "Bahrein"
            case "BD" : return "Bangladesh"
            case "BB" : return "Barbade"
            case "BY" : return "Bélarus"
            case" BE" : return "Belgique"
            case "BZ" : return "Bélize"
            case "BJ" : return "Bénin"
            case "BM" : return "Bermudes"
            case "BT" : return "Bhoutan"
            case "BO" : return "Bolivie (État plurinational de)"
            case "BQ" : return "Bonaire, Saint-Eustache et Saba"
            case "BA" : return "Bosnie-Herzégovine"
            case "BW" : return "Botswana"
            case "BV" : return "Bouvet, Ile"
            case "BR" : return "Brésil"
            case "BN" : return "Brunéi Darussalam"
            case "BG" : return "Bulgarie"
            case "BF" : return "Burkina Faso"
            case "BI" : return "Burundi"
            case "CV" : return "Cabo Verde"
            case "KY" : return "Caïmans, Iles"
            case "KH" : return "Cambodge"
            case "CM" : return "Cameroun"
            case "CA" : return "Canada"
            case "CL" : return "Chili"
            case "CN" : return "Chine"
            case "CX" : return "Christmas, île"
            case "CY" : return "Chypre"
            case "CC" : return "Cocos/Keeling (Îles)"
            case "CO" : return "Colombie"
            case "KM" : return "Comores"
            case "CG" : return "Congo"
            case "CD" : return "Congo, République démocratique du"
            case "CK" : return "Cook, Iles"
            case "KR" : return "Corée, République de"
            case "KP" : return "Corée, République populaire démocratique de"
            case "CR" : return "Costa Rica"
            case "CI" : return "Côte d'Ivoire"
            case "HR" : return "Croatie"
            case "CU" : return "Cuba"
            case "CW" : return "Curaçao"
            case "DK" : return "Danemark"
            case "DJ" : return "Djibouti"
            case "DO" : return "Dominicaine, République"
            case "DM" : return "Dominique"
            case "EG" : return "Egypte"
            case "SV" : return "El Salvador"
            case "AE" : return "Emirats arabes unis"
            case "EC" : return "Equateur"
            case "ER" : return "Erythrée"
            case "ES" : return "Espagne"
            case "EE" : return "Estonie"
            case "US" : return "Etats-Unis d'Amérique"
            case "ET" : return "Ethiopie"
            case "FK" : return "Falkland/Malouines (Îles)"
            case "FO" : return "Féroé, îles"
            case "FJ" : return "Fidji"
            case "FI" : return "Finlande"
            case "GA" : return "Gabon"
            case "GM" : return "Gambie"
            case "GE" : return "Géorgie"
            case "GS" : return "Géorgie du sud et les îles Sandwich du sud"
            case "GH" : return "Ghana"
            case "GI" : return "Gibraltar"
            case "GR" : return "Grèce"
            case "GD" : return "Grenade"
            case "GL" : return "Groenland"
            case "GP" : return "Guadeloupe"
            case "GU" : return "Guam"
            case "GT" : return "Guatemala"
            case "GG" : return "Guernesey"
            case "GN" : return "Guinée"
            case "GW" : return "Guinée-Bissau"
            case "GQ" : return "Guinée équatoriale"
            case "GY" : return "Guyana"
            case "GF" : return "Guyane française"
            case "HT" : return "Haïti"
            case "HM" : return "Heard, Ile et MacDonald, îles"
            case "HN" : return "Honduras"
            case "HK" : return "Hong Kong"
            case "HU" : return "Hongrie"
            case "IM" : return "Île de Man"
            case "UM" : return "Îles mineures éloignées des Etats-Unis"
            case "VG" : return "Îles vierges britanniques"
            case "VI" : return "Îles vierges des Etats-Unis"
            case "IN" : return "Inde"
            case "IO" : return "Indien (Territoire britannique de l'océan)"
            case "ID" : return "Indonésie"
            case "IR" : return "Iran, République islamique d'"
            case "IQ" : return "Iraq"
            case "IE" : return "Irlande"
            case "IS" : return "Islande"
            case "IL" : return "Israël"
            case "IT" : return "Italie"
            case "JM" : return "Jamaïque"
            case "JP" : return "Japon"
            case "JE" : return "Jersey"
            case "JO" : return "Jordanie"
            case "KZ" : return "Kazakhstan"
            case "KE" : return "Kenya"
            case "KG" : return "Kirghizistan"
            case "KI" : return "Kiribati"
            case "KW" : return "Koweït"
            case "LA" : return "Lao, République démocratique populaire"
            case "LS" : return "Lesotho"
            case "LV" : return "Lettonie"
            case "LB" : return "Liban"
            case "LR" : return "Libéria"
            case "LY" : return "Libye"
            case "LI" : return "Liechtenstein"
            case "LT" : return "Lituanie"
            case "LU" : return "Luxembourg"
            case "MO" : return "Macao"
            case "MK" : return "Macédoine, l'ex-République yougoslave de"
            case "MG" : return "Madagascar"
            case "MY" : return "Malaisie"
            case "MW" : return "Malawi"
            case "MV" : return "Maldives"
            case "ML" : return "Mali"
            case "MT" : return "Malte"
            case "MP" : return "Mariannes du nord, Iles"
            case "MA" : return "Maroc"
            case "MH" : return "Marshall, Iles"
            case "MQ" : return "Martinique"
            case "MU" : return "Maurice"
            case "MR" : return "Mauritanie"
            case "YT" : return "Mayotte"
            case "MX" : return "Mexique"
            case "FM" : return "Micronésie, Etats Fédérés de"
            case "MD" : return "Moldova, République de"
            case "MC" : return "Monaco"
            case "MN" : return "Mongolie"
            case "ME" : return "Monténégro"
            case "MS" : return "Montserrat"
            case "MZ" : return "Mozambique"
            case "MM" : return "Myanmar"
            case "NA" : return "Namibie"
            case "NR" : return "Nauru"
            case "NP" : return "Népal"
            case "NI" : return "Nicaragua"
            case "NE" : return "Niger"
            case "NG" : return "Nigéria"
            case "NU" : return "Niue"
            case "NF" : return "Norfolk, Ile"
            case "NO" : return "Norvège"
            case "NC" : return "Nouvelle-Calédonie"
            case "NZ" : return "Nouvelle-Zélande"
            case "OM" : return "Oman"
            case "UG" : return "Ouganda"
            case "UZ" : return "Ouzbékistan"
            case "PK" : return "Pakistan"
            case "PW" : return "Palaos"
            case "PS" : return "Palestine, Etat de"
            case "PA" : return "Panama"
            case "PG" : return "Papouasie-Nouvelle-Guinée"
            case "PY" : return "Paraguay"
            case "NL" : return "Pays-Bas"
            case "XX" : return "Pays inconnu"
            case "ZZ" : return "Pays multiples"
            case "PE" : return "Pérou"
            case "PH" : return "Philippines"
            case "PN" : return "Pitcairn"
            case "PL" : return "Pologne"
            case "PF" : return "Polynésie française"
            case "PR" : return "Porto Rico"
            case "PT" : return "Portugal"
            case "QA" : return "Qatar"
            case "SY" : return "République arabe syrienne"
            case "CF" : return "République centrafricaine"
            case "RE" : return "Réunion"
            case "RO" : return "Roumanie"
            case "GB" : return "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord"
            case "RU" : return "Russie, Fédération de"
            case "RW" : return "Rwanda"
            case "EH" : return "Sahara occidental"
            case "BL" : return "Saint-Barthélemy"
            case "KN" : return "Saint-Kitts-et-Nevis"
            case "SM" : return "Saint-Marin"
            case "MF" : return "Saint-Martin (partie française)"
            case "SX" : return "Saint-Martin (partie néerlandaise)"
            case "PM" : return "Saint-Pierre-et-Miquelon"
            case "VA" : return "Saint-Siège"
            case "VC" : return "Saint-Vincent-et-les-Grenadines"
            case "SH" : return "Sainte-Hélène, Ascension et Tristan da Cunha"
            case "LC" : return "Sainte-Lucie"
            case "SB" : return "Salomon, Iles"
            case "WS" : return "Samoa"
            case "AS" : return "Samoa américaines"
            case "ST" : return "Sao Tomé-et-Principe"
            case "SN" : return "Sénégal"
            case "RS" : return "Serbie"
            case "SC" : return "Seychelles"
            case "SL" : return "Sierra Leone"
            case "SG" : return "Singapour"
            case "SK" : return "Slovaquie"
            case "SI" : return "Slovénie"
            case "SO" : return "Somalie"
            case "SD" : return "Soudan"
            case "SS" : return "Soudan du Sud"
            case "LK" : return "Sri Lanka"
            case "SE" : return "Suède"
            case "CH" : return "Suisse"
            case "SR" : return "Suriname"
            case "SJ" : return "Svalbard et île Jan Mayen"
            case "SZ" : return "Swaziland"
            case "TJ" : return "Tadjikistan"
            case "TW" : return "Taïwan, Province de Chine"
            case "TZ" : return "Tanzanie, République unie de"
            case "TD" : return "Tchad"
            case "CS" : return "Tchécoslovaquie"
            case "CZ" : return "Tchèque, République"
            case "TF" : return "Terres australes françaises"
            case "TH" : return "Thaïlande"
            case "TL" : return "Timor-Leste"
            case "TG" : return "Togo"
            case "TK" : return "Tokelau"
            case "TO" : return "Tonga"
            case "TT" : return "Trinité-et-Tobago"
            case "TN" : return "Tunisie"
            case "TM" : return "Turkménistan"
            case "TC" : return "Turks-et-Caïcos (Îles)"
            case "TR" : return "Turquie"
            case "TV" : return "Tuvalu"
            case "UA" : return "Ukraine"
            case "SU" : return "URSS"
            case "UY" : return "Uruguay"
            case "VU" : return "Vanuatu"
            case "VE" : return "Venezuela (République bolivarienne du)"
            case "VN" : return "Viet Nam"
            case "VD" : return "Viet Nam (Sud)"
            case "WF" : return "Wallis et Futuna"
            case "YE" : return "Yémen"
            case "YU" : return "Yougoslavie"
            case "ZR" : return "Zaïre"
            case "ZM" : return "Zambie"
            case "ZW" : return "Zimbabwe"
            default : return "pays inconu"
        }
    }
}
